# Generated by Django 3.0.3 on 2020-08-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200803_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='color',
            field=models.CharField(default='w3-text-light-green', max_length=300),
        ),
    ]
