# Generated by Django 3.0.3 on 2020-08-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reply_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='color',
            new_name='color_style',
        ),
    ]
