# Generated by Django 3.0.3 on 2020-08-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200804_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='to_reply',
            field=models.IntegerField(default=None),
        ),
    ]
