# Generated by Django 3.0.3 on 2020-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200805_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.AddField(
            model_name='reply',
            name='postId',
            field=models.IntegerField(default=None),
        ),
    ]
