# Generated by Django 3.0.3 on 2020-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200805_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='postId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='to_reply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
