# Generated by Django 3.0.3 on 2020-08-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200805_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='color_style',
            field=models.CharField(default='w3-flat-nephritis', max_length=300),
        ),
    ]
