# Generated by Django 3.0.3 on 2020-08-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='age',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='learning',
            old_name='salary',
            new_name='y',
        ),
    ]
