# Generated by Django 3.0.3 on 2020-08-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0002_auto_20200807_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='y',
            field=models.FloatField(),
        ),
    ]
